sudo: required

services:
  - docker

branches:
  only:
    - master

language: node_js
node_js:
  - 8.0.0

cache:
  yarn: true

env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_b022ca59054f_key -iv $encrypted_b022ca59054f_iv -in ./infrastructure/service-account.json.enc -out ./infrastructure/service-account.json -d;
  - openssl aes-256-cbc -K $encrypted_febce635e7df_key -iv $encrypted_febce635e7df_iv -in ./infrastructure/storage-service-account.json.enc -out ./infrastructure/storage-service-account.json -d;

script:
  - npm run lint
  - npm run test:coverage
  - npm run codacy:coverage

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      git config credential.helper "store --file=.git/credentials";
      echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials;
      bash ./.travis.d/tag-version.sh;
      bash ./.travis.d/gcp-auth.sh;
      bash ./.travis.d/docker-push.sh;
      bash ./.travis.d/update-infra.sh;
    fi
