notifications:
    slack: westernregister:wfxZXrq7fWo3gPB1Cdzaw6lZ

sudo: required

services:
  - docker

branches:
  only:
    - master

language: node_js
node_js:
  - 8.0.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_febce635e7df_key -iv $encrypted_febce635e7df_iv -in ./infrastructure/service-account.json.enc -out ./infrastructure/service-account.json -d
  - openssl aes-256-cbc -K $encrypted_febce635e7df_key -iv $encrypted_febce635e7df_iv -in ./infrastructure/storage-service-account.json.enc -out ./infrastructure/storage-service-account.json -d
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - yarn

script:
  - npm run lint
  - npm run test:coverage
  - npm run publish:coverage

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      git config credential.helper "store --file=.git/credentials";
      echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials;
      bash ./.travis.d/tag-version.sh;
      bash ./.travis.d/gcp-auth.sh;
      bash ./.travis.d/docker-push.sh;
      bash ./.travis.d/update-infra.sh;
    fi
