export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const LOAD_ITEMS_FAILURE = "LOAD_ITEMS_FAILURE";

export const XHR_CALL_START = "XHR_CALL_START";
export const XHR_CALL_FAILURE = "XHR_CALL_FAILURE";