export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_ITEMS_FAILURE = 'LOAD_ITEMS_FAILURE';
export const ITEM_CHECKED = 'ITEM_CHECKED';

export const ITEM_UPDATED = 'ITEM_UPDATED';
export const ITEM_CREATED = 'ITEM_CREATED';

export const ITEM_DEACTIVATED_SUCCESS = 'ITEM_DEACTIVATED_SUCCESS';
export const ITEM_DEACTIVATED = 'ITEM_DEACTIVATED';
export const ITEM_PREVIEW_UPDATED = 'ITEM_PREVIEW_UPDATED';

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';

export const LOAD_DISCOUNTS_SUCCESS = 'LOAD_DISCOUNTS_SUCCESS';

export const LOAD_MODIFIERS_SUCCESS = 'LOAD_MODIFIERS_SUCCESS';

export const LOAD_TAXES_SUCCESS = 'LOAD_TAXES_SUCCESS';

export const LOAD_REFUNDREASONS_SUCCESS = 'LOAD_REFUNDREASONS_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const XHR_CALL_START = 'XHR_CALL_START';
export const XHR_CALL_SUCCESS = 'XHR_CALL_SUCCESS';
export const XHR_CALL_FAILURE = 'XHR_CALL_FAILURE';

export const LOAD_VERSION_SUCCESS = 'LOAD_VERSION_SUCCESS';

export const LOADING_USER = 'LOADING_USER';
export const LOADING_CREATING_ITEM = 'LOADING_CREATING_ITEM';

export const LOADING_ITEM_CREATION = 'LOADING_ITEM_CREATION';
export const LOADING_ITEM_CREATION_SUCCESS = 'LOADING_ITEM_CREATION_SUCCESS';
export const ITEM_CREATION_FAILURE = 'ITEM_CREATION_FAILURE';

export const LOADING_ITEM_UPDATE = 'LOADING_ITEM_UPDATE';
export const LOADING_ITEM_UPDATE_SUCCESS = 'LOADING_ITEM_UPDATE_SUCCESS';
export const ITEM_UPDATE_FAILURE = 'ITEM_UPDATE_FAILURE';

export const LOADED_USER_SUCCESS = 'LOADED_USER_SUCCESS';
export const LOADED_USER_FAILURE = 'LOADED_USER_FAILURE';


export const CATEGORY_DEACTIVATED = 'CATEGORY_DEACTIVATED';
export const CATEGORY_DEACTIVATED_SUCCESS = 'CATEGORY_DEACTIVATED_SUCCESS';
export const LOADING_CATEGORY_CREATION = 'LOADING_CATEGORY_CREATION';
export const LOADING_CATEGORY_CREATION_SUCCESS = 'LOADING_CATEGORY_CREATION_SUCCESS';
export const CATEGORY_CREATION_FAILURE = 'CATEGORY_CREATION_FAILURE';
export const CATEGORY_CREATED = 'CATEGORY_CREATED';
export const LOADING_CATEGORY_UPDATE = 'LOADING_CATEGORY_UPDATE';
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED';
export const LOADING_CATEGORY_UPDATE_SUCCESS = 'LOADING_CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAILURE = 'CATEGORY_UPDATE_FAILURE';

export const TAX_DEACTIVATED = 'TAX_DEACTIVATED';
export const TAX_DEACTIVATED_SUCCESS = 'TAX_DEACTIVATED_SUCCESS';
export const LOADING_TAX_CREATION = 'LOADING_TAX_CREATION';
export const LOADING_TAX_CREATION_SUCCESS = 'LOADING_TAX_CREATION_SUCCESS';
export const TAX_CREATION_FAILURE = 'TAX_CREATION_FAILURE';
export const TAX_CREATED = 'TAX_CREATED';
export const LOADING_TAX_UPDATE = 'LOADING_TAX_UPDATE';
export const TAX_UPDATED = 'TAX_UPDATED';
export const LOADING_TAX_UPDATE_SUCCESS = 'LOADING_TAX_UPDATE_SUCCESS';
export const TAX_UPDATE_FAILURE = 'TAX_UPDATE_FAILURE';

export const MODIFIER_DEACTIVATED = 'MODIFIER_DEACTIVATED';
export const MODIFIER_DEACTIVATED_SUCCESS = 'MODIFIER_DEACTIVATED_SUCCESS';
export const LOADING_MODIFIER_CREATION = 'LOADING_MODIFIER_CREATION';
export const LOADING_MODIFIER_CREATION_SUCCESS = 'LOADING_MODIFIER_CREATION_SUCCESS';
export const MODIFIER_CREATION_FAILURE = 'MODIFIER_CREATION_FAILURE';
export const MODIFIER_CREATED = 'MODIFIER_CREATED';
export const LOADING_MODIFIER_UPDATE = 'LOADING_MODIFIER_UPDATE';
export const MODIFIER_UPDATED = 'MODIFIER_UPDATED';
export const LOADING_MODIFIER_UPDATE_SUCCESS = 'LOADING_MODIFIER_UPDATE_SUCCESS';
export const MODIFIER_UPDATE_FAILURE = 'MODIFIER_UPDATE_FAILURE';

export const DISCOUNT_DEACTIVATED = 'DISCOUNT_DEACTIVATED';
export const DISCOUNT_DEACTIVATED_SUCCESS = 'DISCOUNT_DEACTIVATED_SUCCESS';
export const LOADING_DISCOUNT_CREATION = 'LOADING_DISCOUNT_CREATION';
export const LOADING_DISCOUNT_CREATION_SUCCESS = 'LOADING_DISCOUNT_CREATION_SUCCESS';
export const DISCOUNT_CREATION_FAILURE = 'DISCOUNT_CREATION_FAILURE';
export const DISCOUNT_CREATED = 'DISCOUNT_CREATED';
export const LOADING_DISCOUNT_UPDATE = 'LOADING_DISCOUNT_UPDATE';
export const DISCOUNT_UPDATED = 'DISCOUNT_UPDATED';
export const LOADING_DISCOUNT_UPDATE_SUCCESS = 'LOADING_DISCOUNT_UPDATE_SUCCESS';
export const DISCOUNT_UPDATE_FAILURE = 'DISCOUNT_UPDATE_FAILURE';
