export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const LOAD_ITEMS_FAILURE = "LOAD_ITEMS_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const XHR_CALL_START = "XHR_CALL_START";
export const XHR_CALL_FAILURE = "XHR_CALL_FAILURE";