resources:
- name: mdjs-kube
  type: container.v1.cluster
  properties:
    zone: us-central1-a
    cluster:
      description: Merchant Dashboard Cluster
      initialClusterVersion: 1.7.0
      nodePools:
        - name: merchant-dashboard-pool
          initialNodeCount: 1
          autoscaling: 
            enabled: true
            minNodeCount: 1 
            maxNodeCount: 3
          config:
            machineType: n1-standard-1
            diskSizeGb: 100
            serviceAccount: default
            oauthScopes:
              - https://www.googleapis.com/auth/compute
              - https://www.googleapis.com/auth/devstorage.read_only
              - https://www.googleapis.com/auth/service.management.readonly
              - https://www.googleapis.com/auth/servicecontrol
              - https://www.googleapis.com/auth/logging.write
              - https://www.googleapis.com/auth/trace.append
              - https://www.googleapis.com/auth/monitoring
              - https://www.googleapis.com/auth/cloud_debugger
            labels:
              env: dev
      loggingService: logging.googleapis.com
      monitoringService: monitoring.googleapis.com
      network: default
      addonsConfig:
          horizontalPodAutoscaling:
            disabled: false
          httpLoadBalancing:
            disabled: false
      network: default

# Configuration File Documentation
# https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters#Cluster

# Node Configuration
# https://cloud.google.com/container-engine/reference/rest/v1/NodeConfig

# Machine Types
# https://cloud.google.com/compute/docs/machine-types

# Node Pools
# https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters.nodePools#NodePool

# Deploying via DeploymentManager(running from the root):
# gcloud deployment-manager deployments create mdjs-kube-deployment --config ./infrastructure/cluster.yaml
