---
swagger: "2.0"
info:
  description: "REST API that expresses operations against mdjs.io"
  version: "1.0.0"
  title: "MDJS"
  contact: {}
consumes:
- "application/json"
produces:
- "application/json"
security:
- Basic authentication: []
paths:
  /categories:
    get:
      summary: "Get a collection of categories"
      description: "Get a collection of categories"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
        description: "A uuid of the auth token"
        x-example: "7daaa294-b2f3-439b-b491-738ddb72080d"
      responses:
        200:
          description: "Status 200"
securityDefinitions:
  Basic authentication:
    type: "basic"
definitions:
  CategoriesCollection:
    type: "object"
    required:
    - "categoryID"
    - "categoryName"
    - "companyID"
    - "createdBy"
    - "createdDate"
    - "facilityID"
    - "isActive"
    - "items"
    - "lastUpdatedBy"
    - "lastUpdatedDate"
    properties:
      categoryID:
        type: "number"
        description: "The id of the category"
        example: 65
      categoryName:
        type: "string"
        description: "The name of the category"
        example: "food"
      items:
        type: "array"
        description: "The array of item ids that roll up to this category"
        items:
          type: "number"
          example: 54
      lastUpdatedDate:
        type: "string"
        description: "string representation of the updated date"
        example: "2017-08-18T00:00:39.567"
      createdDate:
        type: "string"
        description: "string representation of the created date"
        example: "2017-03-31T00:42:47.33"
      lastUpdatedBy:
        type: "number"
        description: "The id of the user that updated the category last"
        example: 6
      createdBy:
        type: "number"
        description: "The id of the user that created the category"
        example: 6
      isActive:
        type: "boolean"
        description: "A representation of whether or not the category is currently\
          \ active"
        example: true
      companyID:
        type: "number"
        description: "The id of the company"
        example: 12
      facilityID:
        type: "number"
        description: "The id of the facility"
        example: 1
